on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm i
      - run: cd src
      - name: Store current directory
          run: |
            current_dir=$(pwd)
            echo "Current directory: ${current_dir}"
      - run: node Index.js