version: 0.2

phases:
  install:
    commands:
      - apt-get install zip
      - apt-get install libfontconfig
      - apt-get install libfreetype6
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - ls -R
      - npm install
      - cd src
      - node index.js
